#+TITLE: The creature, the gentleman and the king
#+DESCRIPTION: Blog for my projects and random thoughts
#+SETUPFILE:  ../../pages/level-2.org
#+INCLUDE: ../../sitemap.org

* The creature, the gentleman and the king
:PROPERTIES:
:ID:       1BE3243C-DD4B-4B72-A062-FFFFA010355D
:END:
Once upon a time, there was a land filled with retirees in a kingdom far, far away. These elderly people might have been old, but were still very much young at heart. However, the land was much too big, and all lived at a great distance from one another, making contact difficult. These were trying times, as a new disease called "loneliness" ravaged the lands.


One day, the king decided to summon his counsel and ordered them to develop new and innovative ways to combat this "loneliness." But all the kings' horses, and all the kings' men, could not make the land great again. The "loneliness" kept on with it's devouring appetite, and people even spoke of a situation of pandemic proportions. And so it was, for months, the kingdom was as if it was shut down. It's citizens experiencing loneliness so profound; they did not want to come out of bed anymore.


At one Thursday morning, somewhere in July, a peculiar little creature popped up. It had pointy ears, big eyes, and wearing nothing but a raggedy cushion cover and one single sock. Looking dazed, it slowly stumbled towards a big fallen oak tree. As it sat there, for three hours long, it pondered where it was, and how it got there. Especially the "where" of it all was quite the conundrum. It had already become midday by this time, and the creature set out to find someone to talk to.


Two days went by, and the little creature did not find anyone until it stumbled onto what seemed to be an abandoned house. At least, so it seemed. The creature knocked on the door, and no one answered. It walked around to the garden, and no one was there. It even climbed up on the roof to look through the windows, but they were so dirty that it could not even see through them. The little creature was just about to give up when he saw a tiny window open on the side of the house. Being of a very small stature himself, he had no difficulty in climbing through. Though it was nervous, it had to find at least a place to sleep. First, there was a large and dusty living room. Then, a cold hallway tiled with marble stones leading to a wooden carved stairway. Up the stairs, the creature went, when a glimpse of movement caught his eye.


A PERSON!


Quickly and overeagerly, he ran towards the room. There was a queen-sized bed with an older gentleman in it. The gentleman was startled and hid under the covers, hoping that the creature would go away. But the creature did not go away; it even spoke to him. It noticed how frightened the man was and immediately calmed down. "Hello, I'm awfully sorry to barge in like this," the creature said. "May I ask you what your name is? Mine is Dobby.". The gentleman was so captured by Dobby's politeness and warm voice that he could not help but feeling calmed down. "Robert... My name is Robert.", he said. Robert, who had not seen anyone in what seems to be forever, was filled with glee and confusion. Another person!


As Dobby and Robert were glad to have finally found someone, they began to talk. After conversing for hours on end until it became dark outside, Dobby queried an especially important question. "Where is everyone?" asked Dobby. Robert reacted with silence. A silence broken by a tear that rolled down from his cheek, after which he replied: "The loneliness... The loneliness has gotten a hold of all of us. Even the king attempted to make things right, but no one succeeded...". Dobby sat there and thought about what exactly loneliness was. Loneliness is a distressing experience when a person's social relationships are perceived to be less in quantity, especially in quality, than desired. While Dobby sat there, thinking, Robert went to bed as it was already far beyond midnight. Dobby, however, stayed and pondered. Social relationships that are perceived less in quantity and especially in quality... What can help? What can bring people together? What can bridge these vast distances and combat this "loneliness"? Dobby sat quietly, thinking until he fell asleep.


A rumbling sound. There was a rumbling sound coming from downstairs, and a fantastic smell welcomed Dobby back to reality. He went downstairs only to find Robert up and about, happily making breakfast for the both of them. Robert greeted Dobby with a grand smile, and then a moment! A special eureka moment! Dobby had found what he spent all night looking for and was overjoyed. "Personal contact!" screamed Dobby. "Personal, meaningful contact with other people!". Robert looked confused and asked what Dobby was trying to tell him. Back where Dobby was from, there was this magical thing called the internet. And the internet could connect people with strange contraptions called "phones". A rather silly name, but they held great powers of communication. In these "phones," people could play games, talk to one another, and send snapshots of pretty much anything! "With these phones, we could connect these people living in isolation! They could talk to each other all the time, just like we did last night," said Dobby. Robert was so excited about this story that he forgot that he was cooking and accidentally burned his specialty dish, eggs benedict. He told about a treasure chest that the king had for innovative projects, which he called the National Wellbeing Operation (NWO). The NWO was explicitly set up to fund new projects that showed great promise to increase the kingdoms' wellbeing. Dobby felt they were onto something significant, and Robert suggested going to the king as soon as possible. They got ready, ate the burned eggs benedict that has never tasted better, and left.


A long and arduous journey ensued. A journey containing enough material to cover several books had come to an end. The two travelers had reached the castle of the king.


An open gate, an empty hall, a dusty dining room were all that reminded Dobby about his first encounter with Robert. On arriving at the kingly bedroom, there was a man. Big in stature, but small in demeanor. A man who has long forgotten his ruling position as he roamed the castle day in, day out until he had become bedridden. Upon seeing the two travelers, a sea of emotions swept over him. Surprised, frightened, and happy were only some of his feelings when Dobby first spoke to him. To calm the king, Robert took everyone to the royal kitchen and made his improved signature dish, burned eggs benedict.


After being calmed down, Dobby went on to explain his ideas. The internet, the phones, and the NWO funding that would be needed to create an application that could connect all the kingdom's senior citizens. Having heard everything, the king sat quietly. Was this the answer to his problems? Could this project be the remedy to loneliness? He stood up and walked out onto the courtyard. With each step, it seemed that his back straightened up more and more until his small demeanor changed into an impressive display of authority. He laughed loudly and yelled: "Of course you can have funding, I am completely at your service!". The king foresaw one issue, though. The internet of which Dobby spoke was no easy thing to obtain. It was guarded in the black forest by a mighty fairy queen named Fay. If the plan were to succeed, they would need to convince Fay to share her precious internet with the world.


Filled with renewed energy, the three companions left to the black forest. After a journey with many perils and adventures that would be told for generations to come, they finally arrived. There was a beautiful treehouse that grew in a way that the three travelers had never seen before. Long spirals of black wood reached as far as the eyes can see, and a single staircase that went up far beyond the forest canopy from back home. They went up and walked on the tune of what seemed like a thousand birds singing in perfect unison. Arriving at the top, there was a pond with frogs the size of horses and someone sitting at the end, wearing the most beautiful crown made out of golden leaves and silver flowers. It was queen Fay, already waiting for their arrival as the woods themselves had already informed her there were strangers in her forest. She stood up, spread her wings, and as if instantaneous, she flew towards the traveling fellowship. Hovering quietly in the air, she inquired about their purpose. She demanded them to explain quickly and concisely as she was not known for her patience. The king stepped forward and kneeled before queen Faye. "My kingdom has befallen great tragedy, my queen. An illness named 'loneliness' has ravaged over my lands. It is our belief that the internet you hold power over could be the answer to our suffering. Our brave friend and scholar called Dobby has proved himself able to research and possibly rid my kingdom of loneliness with something called an app, which requires access to your internet".


The queen's face was stern, as she did not understand this concept of loneliness. She looked at Dobby and asked him to explain. "It is our belief that loneliness is an unpleasant emotional response to perceived isolation. A type of social pain that can lie at the root of many issues, both psychological and physical. Our quest entails removing this ailment from the people by creating a communication platform that is a playful virtual environment to share one's experiences and make new ones. This application will monitor and optimize social interaction as it develops and deepens its users' relationships." The queen found difficulty in this concept, as she was never alone. She interacted with the birds, the frogs, and even the forest itself. As such, she had never known such a painful silence in her life. However, she could understand when thinking about losing her forest. This was a chilling thought which caused her to agree and provide access to the internet.


The fellowship was happy that they could finally start their research, but all knew that they still had a long way to go. A total of four years passed in which several ups and downs were posed. An arduous road that eventually led to the application Dobby has dreamed about. As they released it, it spread like wildfire. Every single person in the kingdom started playing, talking, laughing with one another. The loneliness had finally subsided. Dobby was awarded the medal of doctorship and a fresh set of clean clothes. However, there was one piece of clothing that Dobby did not want to part from. The one single sock that held special meaning to him.


And they lived happily ever after.
